# Generated by Django 5.0.6 on 2024-07-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_product_demo_url_product_product_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='download',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
    ]
